### ISSUE TITLE
Ambiguity in math problems and module.

### ISSUE THREAD

**Issue by ash2shukla** [RafaelBroseghini/CommuniPy#20]
math problems file is named math.py,  if someone tries to import math in it, it will import itself.

https://github.com/RafaelBroseghini/CommuniPy/blob/e8057661b22ca122ff35eebaf70aa2c8a867fec8/Practice%20Problems/05-Math/01-Beginner/math.py#L3-L4

Instead of resolving the name problem comment is given that assume values instead of importing?

it should be renamed to __maths.py__

https://github.com/RafaelBroseghini/CommuniPy/blob/e8057661b22ca122ff35eebaf70aa2c8a867fec8/Practice%20Problems/05-Math/01-Beginner/math.py#L12-L17

Problem doesn't state what to do when number is negative, neither it says that number will only be positive.
Give proper conditions for input.

https://github.com/RafaelBroseghini/CommuniPy/blob/e8057661b22ca122ff35eebaf70aa2c8a867fec8/Practice%20Problems/05-Math/01-Beginner/math.py#L6-L10

Tell explicitly what to return eg.

```python
"""
        Given a number, return string 'even' if it is even or 'odd' if it is odd.
"""
```

**Comment by RafaelBroseghini** [comment]
Good catches! Mind fixing? Thanks!
