### ISSUE TITLE
Syntactical Problems in old TestCases.

### ISSUE THREAD

**Issue by ash2shukla** [RafaelBroseghini/CommuniPy#21]
https://github.com/RafaelBroseghini/CommuniPy/blob/e8057661b22ca122ff35eebaf70aa2c8a867fec8/Practice%20Problems/01-Strings/Beginner/test_strings.py#L5

Instead of naming them Testers these should be named as <ProblemType><DifficultyLeve><TestCase>
eg. StringsBeginnerTestCase.

https://github.com/RafaelBroseghini/CommuniPy/blob/e8057661b22ca122ff35eebaf70aa2c8a867fec8/Practice%20Problems/01-Strings/Beginner/test_strings.py#L11

Change the print statements to

```python
print("\n.Passed 1. reverse_string with no errors!")
```

**Comment by ash2shukla** [comment]
https://github.com/RafaelBroseghini/CommuniPy/blob/e8057661b22ca122ff35eebaf70aa2c8a867fec8/Practice%20Problems/01-Strings/Beginner/test_strings.py#L34

This TestCase should assert to False.

**Comment by RafaelBroseghini** [comment]
I will fix this one :) Thanks again!

**Comment by RafaelBroseghini** [comment]
Also, you deserve a spot in the contributors section :)

**Comment by ash2shukla** [comment]
Fixed in this pr.
