### ISSUE TITLE
Inconsistent and Improper Indents. add Guidelines to CONTRIBUTING.md

### ISSUE THREAD

**Issue by ash2shukla** [RafaelBroseghini/CommuniPy#22]
https://github.com/RafaelBroseghini/CommuniPy/blob/e8057661b22ca122ff35eebaf70aa2c8a867fec8/Practice%20Problems/03-Dictionaries/Beginner/test_dicts.py#L10

Extra space causing test case to fail.

https://github.com/RafaelBroseghini/CommuniPy/blob/e8057661b22ca122ff35eebaf70aa2c8a867fec8/Practice%20Problems/05-Math/01-Beginner/math.py#L7-L9

Improper indents make files look inconsistent.

Many pushes have these naive mistakes which make practice files look weird. Please add guidelines to CONTRIBUTING.md about submitting PEP8 compliant code or better, define standards by giving a template for additions.

**Comment by RafaelBroseghini** [comment]
Mind opening a pr? Thanks a lot!

**Comment by ash2shukla** [comment]
Fixed previous mistakes in this, you can decide on the CONTRIBUTING.md and push accordingly.
